version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: pls-postgres
    environment:
      POSTGRES_DB: pls_backend
      POSTGRES_USER: ssingh83
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
